[project]
name = "the-good-bot"
version = "0.1.0"
description = "Discord bot to handle obsidian tasks"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "discord-py>=2.4.0",
    "python-dotenv>=1.0.1",
]
